1.                                               Create a white box neural network

In [2]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Define a modified feedforward neural network
def create_white_box_nn_modified(input_shape):
    model = models.Sequential()

    # Input layer
    model.add(layers.InputLayer(input_shape=input_shape))

    # Hidden layers (modified)
    model.add(layers.Dense(units=256, activation='elu'))  # Increased units and changed activation
    model.add(layers.Dense(units=128, activation='selu'))  # Changed activation

    # Output layer
    model.add(layers.Dense(units=1, activation='sigmoid'))

    return model

# Specify input shape (assuming a binary classification task with input features of size 10)
input_shape = (10,)

# Create the modified white-box neural network
white_box_nn_modified = create_white_box_nn_modified(input_shape)

# Display the model summary
white_box_nn_modified.summary()

/Users/mohamedneinahasan/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 256)               2816      
                                                                 
 dense_1 (Dense)             (None, 128)               32896     
                                                                 
 dense_2 (Dense)             (None, 1)                 129       
                                                                 
Total params: 35841 (140.00 KB)
Trainable params: 35841 (140.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


2.                                                         Activation functions

1. Sigmoid function

In [3]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Using numpy for vectorized operations
def sigmoid_np(x):
    return 1 / (1 + np.exp(-x))

# Example usage:
result_math = sigmoid(2.0)
result_np = sigmoid_np(np.array([2.0]))

print("Result using math module:", result_math)
print("Result using NumPy:", result_np)


Result using math module: 0.8807970779778823
Result using NumPy: [0.88079708]


2. tanh function


In [5]:
import numpy as np

def tanh(x):
    return (np.exp(2*x) - 1) / (np.exp(2*x) + 1)

# Using numpy for vectorized operations
def tanh_np(x):
    return np.tanh(x)

# Example usage:
result_math = tanh(2.0)
result_np = tanh_np(np.array([2.0]))

print("Result using math module:", result_math)
print("Result using NumPy:", result_np)


Result using math module: 0.9640275800758169
Result using NumPy: [0.96402758]


3.RELU function


In [6]:
import numpy as np

def relu(x):
    return max(0, x)

# Using numpy for vectorized operations
def relu_np(x):
    return np.maximum(0, x)

# Example usage:
result_math = relu(2.0)
result_np = relu_np(np.array([2.0]))

print("Result using manual implementation:", result_math)
print("Result using NumPy:", result_np)


Result using manual implementation: 2.0
Result using NumPy: [2.]


4.ELU function


In [7]:
import numpy as np

def elu(x, alpha=1.0):
    return np.where(x >= 0, x, alpha * (np.exp(x) - 1))

# Example usage
x_values = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
output_values = elu(x_values, alpha=1.0)
print(output_values)


[-0.86466472 -0.63212056  0.          1.          2.        ]


5.PRELU function


In [8]:
import numpy as np

class PReLU:
    def __init__(self, alpha=0.01):
        self.alpha = alpha

    def __call__(self, x):
        return np.maximum(0, x) + self.alpha * np.minimum(0, x)

# Example usage
prelu_activation = PReLU(alpha=0.01)
x_values = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
output_values = prelu_activation(x_values)
print(output_values)


[-0.02 -0.01  0.    1.    2.  ]


6.Leaky RELU function


In [9]:
import numpy as np

def leaky_relu(x, alpha=0.01):
    return np.maximum(alpha * x, x)

# Example usage
x_values = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
output_values = leaky_relu(x_values, alpha=0.01)
print(output_values)


[-0.02 -0.01  0.    1.    2.  ]


7.SELU function


In [20]:
import numpy as np

def selu(x, scale=1.0507, alpha=1.67326):
    return scale * np.where(x > 0, x, alpha * (np.exp(x) - 1))

# Example usage
x_values = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
output_values = selu(x_values)
print(output_values)

[-1.52016209 -1.11132754  0.          1.0507      2.1014    ]


8.Softsign function


In [19]:

import numpy as np

def softsign(x):
    return x / (1 + np.abs(x))

# Example usage
x_values = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
output_values = softsign(x_values)
print(output_values)


[-0.66666667 -0.5         0.          0.5         0.66666667]


9.Softplus


In [18]:
import numpy as np

def softplus(x):
    return np.log(1 + np.exp(x))

# Example usage
x_values = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
output_values = softplus(x_values)
print(output_values)

[0.12692801 0.31326169 0.69314718 1.31326169 2.12692801]


10.Hard sigmoid


In [17]:

import numpy as np
def hard_sigmoid(x):
    return np.clip(0.16666667 * x + 0.5, 0, 1)
# Example usage
x_values = np.array([-3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0])
output_values = hard_sigmoid(x_values)
print(output_values)

[0.         0.16666666 0.33333333 0.5        0.66666667 0.83333334
 1.        ]


11.Swish function


In [16]:

import numpy as np

def swish(x):
    return x * (1.0 / (1.0 + np.exp(-x)))

# Example usage
x_values = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
output_values = swish(x_values)
print(output_values)


[-0.23840584 -0.26894142  0.          0.73105858  1.76159416]


12.Mish function


In [15]:
import numpy as np

def mish(x):
    return x * np.tanh(np.log(1 + np.exp(x)))

# Example usage
x_values = np.array([-2.0, -1.0, 0.0, 1.0, 2.0])
output_values = mish(x_values)
print(output_values)


[-0.25250148 -0.30340146  0.          0.86509839  1.94395896]


Python code for chain rule


In [14]:
import sympy as sp

# Define symbols
x = sp.symbols('x')

# Define the inner and outer functions
g = x**2
f = sp.sin(g)

# Compute the derivatives
g_prime = sp.diff(g, x)
f_prime = sp.diff(f, x)

# Apply the chain rule
chain_rule_result = sp.diff(f.subs(g, x**2), x)

# Print the result
print("f'(x) =", f_prime)
print("g'(x) =", g_prime)
print("Chain Rule Result:", chain_rule_result)


f'(x) = 2*x*cos(x**2)
g'(x) = 2*x
Chain Rule Result: 2*x*cos(x**2)


Function to perform back propagation


In [13]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def mean_squared_error(y_true, y_pred):
    return 0.5 * np.mean((y_true - y_pred) ** 2)

def mean_squared_error_derivative(y_true, y_pred):
    return y_pred - y_true

def initialize_weights(input_size, hidden_size, output_size):
    np.random.seed(42)
    weights_input_hidden = np.random.randn(input_size, hidden_size)
    weights_hidden_output = np.random.randn(hidden_size, output_size)
    return weights_input_hidden, weights_hidden_output

def forward_propagation(X, weights_input_hidden, weights_hidden_output):
    hidden_layer_input = np.dot(X, weights_input_hidden)
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
    output_layer_output = sigmoid(output_layer_input)
    return hidden_layer_output, output_layer_output

def backward_propagation(X, y, hidden_layer_output, output_layer_output, 
                         weights_input_hidden, weights_hidden_output, learning_rate):
    output_error = mean_squared_error_derivative(y, output_layer_output)
    output_delta = output_error * sigmoid_derivative(output_layer_output)

    hidden_error = output_delta.dot(weights_hidden_output.T)
    hidden_delta = hidden_error * sigmoid_derivative(hidden_layer_output)

    weights_hidden_output -= hidden_layer_output.T.dot(output_delta) * learning_rate
    weights_input_hidden -= X.T.dot(hidden_delta) * learning_rate

def train_neural_network(X, y, hidden_size, epochs, learning_rate):
    input_size = X.shape[1]
    output_size = 1

    weights_input_hidden, weights_hidden_output = initialize_weights(input_size, hidden_size, output_size)

    for epoch in range(epochs):
        hidden_layer_output, output_layer_output = forward_propagation(X, weights_input_hidden, weights_hidden_output)

        backward_propagation(X, y, hidden_layer_output, output_layer_output, 
                             weights_input_hidden, weights_hidden_output, learning_rate)

        if epoch % 1000 == 0:
            loss = mean_squared_error(y, output_layer_output)
            print(f"Epoch {epoch}, Loss: {loss}")

    return weights_input_hidden, weights_hidden_output

# Example usage
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

trained_weights_input_hidden, trained_weights_hidden_output = train_neural_network(X, y, hidden_size=4, epochs=10000, learning_rate=0.1)

# Test the trained network
_, predictions = forward_propagation(X, trained_weights_input_hidden, trained_weights_hidden_output)
print("\nPredictions:")
print(predictions)


Epoch 0, Loss: 0.14159479453221988
Epoch 1000, Loss: 0.12344689570690472
Epoch 2000, Loss: 0.11155406432451556
Epoch 3000, Loss: 0.07778517861398407
Epoch 4000, Loss: 0.03281496018045563
Epoch 5000, Loss: 0.01479961501423141
Epoch 6000, Loss: 0.008925515193170449
Epoch 7000, Loss: 0.006249858172555918
Epoch 8000, Loss: 0.004750368741015834
Epoch 9000, Loss: 0.0037992877772672767

Predictions:
[[0.09620443]
 [0.92303163]
 [0.92312117]
 [0.06383034]]


Back propagation for ant colony optimization


In [12]:
import numpy as np

# Define the task (e.g., XOR)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Neural network architecture
input_size = 2
hidden_size = 4
output_size = 1

# ACO parameters
num_ants = 5
pheromone_matrix = np.ones((input_size * hidden_size + hidden_size * output_size,))

# Define the sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Define the neural network forward propagation
def forward_propagation(weights, X):
    input_hidden_weights = weights[:input_size * hidden_size].reshape(input_size, hidden_size)
    hidden_output_weights = weights[input_size * hidden_size:].reshape(hidden_size, output_size)

    hidden_layer_input = np.dot(X, input_hidden_weights)
    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_output, hidden_output_weights)
    output_layer_output = sigmoid(output_layer_input)

    return output_layer_output

# Define the fitness function based on mean squared error
def fitness(weights):
    total_error = 0
    for xi, target in zip(X, y):
        output = forward_propagation(weights, xi)
        total_error += np.mean((output - target) ** 2)
    return -total_error  # Maximizing fitness, so negative of error

# ACO-inspired exploration
def explore_weights(pheromone_matrix):
    weights = np.random.rand(len(pheromone_matrix))
    weights = weights * pheromone_matrix
    return weights / np.sum(weights)

# Training loop
num_iterations = 100
learning_rate = 0.1

for iteration in range(num_iterations):
    for ant in range(num_ants):
        # Explore the weight space using ACO
        candidate_weights = explore_weights(pheromone_matrix)

        # Evaluate fitness
        fitness_candidate = fitness(candidate_weights)

        # Update pheromone based on fitness
        pheromone_matrix += learning_rate * (fitness_candidate - pheromone_matrix)

    # Print the best fitness in each iteration
    best_fitness = max(fitness(candidate_weights) for ant in range(num_ants))
    print(f"Iteration {iteration}, Best Fitness: {best_fitness}")

# Get the best weights from the pheromone matrix
best_weights = explore_weights(pheromone_matrix)

# Test the best weights
predictions = [forward_propagation(best_weights, xi) for xi in X]
print("\nFinal Predictions:")
print(predictions)


Iteration 0, Best Fitness: -1.0035493852035713
Iteration 1, Best Fitness: -1.0086646997222268
Iteration 2, Best Fitness: -1.0114553734563616
Iteration 3, Best Fitness: -1.0061845416066555
Iteration 4, Best Fitness: -1.0050921433343987
Iteration 5, Best Fitness: -1.0078150249087314
Iteration 6, Best Fitness: -1.002436433718481
Iteration 7, Best Fitness: -1.006885871098603
Iteration 8, Best Fitness: -1.0088225666852066
Iteration 9, Best Fitness: -1.010326026385033
Iteration 10, Best Fitness: -1.0093474017228852
Iteration 11, Best Fitness: -1.0111540742910003
Iteration 12, Best Fitness: -1.0019213711315988
Iteration 13, Best Fitness: -1.008733668281065
Iteration 14, Best Fitness: -1.0095979055132498
Iteration 15, Best Fitness: -1.0060910984575047
Iteration 16, Best Fitness: -1.0119466457955895
Iteration 17, Best Fitness: -1.0166604296892574
Iteration 18, Best Fitness: -1.0090508291589484
Iteration 19, Best Fitness: -1.0051472001094401
Iteration 20, Best Fitness: -1.0021259690087454
Iterat

Back propagation for genetic algorithm


In [11]:
import numpy as np

# Define the task (e.g., XOR)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Define neural network architecture
input_size = 2
hidden_size = 4
output_size = 1

# Define genetic algorithm parameters
population_size = 10
mutation_rate = 0.1
num_generations = 100

# Initialize the population with random weights
population = [np.random.randn((input_size + 1) * hidden_size + (hidden_size + 1) * output_size) for _ in range(population_size)]

# Define the sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Define the neural network forward propagation
def forward_propagation(weights, X):
    # Extract weights for input to hidden layer and hidden to output layer
    input_hidden_weights = weights[:input_size * hidden_size].reshape(input_size, hidden_size)
    hidden_output_weights = weights[input_size * hidden_size:].reshape(hidden_size, output_size)

    # Input to hidden layer
    hidden_layer_input = np.dot(X, input_hidden_weights)
    hidden_layer_output = sigmoid(hidden_layer_input)

    # Hidden to output layer
    output_layer_input = np.dot(hidden_layer_output, hidden_output_weights)
    output_layer_output = sigmoid(output_layer_input)

    return output_layer_output

# Define the fitness function based on mean squared error
def fitness(weights):
    total_error = 0
    for xi, target in zip(X, y):
        output = forward_propagation(weights, xi)
        total_error += np.mean((output - target) ** 2)
    return -total_error  # Maximizing fitness, so negative of error

# Genetic algorithm loop
for generation in range(num_generations):
    # Evaluate fitness for each individual in the population
    fitness_scores = [fitness(individual) for individual in population]

    # Select parents based on fitness scores (roulette wheel selection)
    parents_indices = np.random.choice(range(population_size), size=2, p=fitness_scores / np.sum(fitness_scores))

    # Crossover (single-point crossover)
    crossover_point = np.random.randint(len(population[0]))
    child1 = np.concatenate((population[parents_indices[0]][:crossover_point], population[parents_indices[1]][crossover_point:]))
    child2 = np.concatenate((population[parents_indices[1]][:crossover_point], population[parents_indices[0]][crossover_point:]))

    # Mutation
    child1[np.random.rand(len(child1)) < mutation_rate] += np.random.randn(sum(np.random.rand(len(child1)) < mutation_rate))
    child2[np.random.rand(len(child2)) < mutation_rate] += np.random.randn(sum(np.random.rand(len(child2)) < mutation_rate))

    # Replace the least fit individuals with the new children
    least_fit_index = np.argmin(fitness_scores)
    population[least_fit_index] = child1
    population[(least_fit_index + 1) % population_size] = child2

    # Print the best fitness in each generation
    best_fitness = max(fitness_scores)
    print(f"Generation {generation}, Best Fitness: {best_fitness}")

# Get the best individual (weights) from the final population
best_weights = population[np.argmax(fitness_scores)]

# Test the best individual
predictions = [forward_propagation(best_weights, xi) for xi in X]
print("\nFinal Predictions:")
print(predictions)


ValueError: cannot reshape array of size 9 into shape (4,1)

Back propagation for cultural algorithm


In [10]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def initialize_weights(input_size, hidden_size, output_size):
    weights_input_hidden = np.random.randn(input_size, hidden_size)
    weights_hidden_output = np.random.randn(hidden_size, output_size)
    return weights_input_hidden, weights_hidden_output

def forward_propagation(X, weights_input_hidden, weights_hidden_output):
    hidden_layer_input = np.dot(X, weights_input_hidden)
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
    output_layer_output = sigmoid(output_layer_input)
    return hidden_layer_output, output_layer_output

def backpropagation(X, y, hidden_layer_output, output_layer_output, weights_hidden_output):
    output_error = y - output_layer_output
    output_delta = output_error * sigmoid_derivative(output_layer_output)
    hidden_error = output_delta.dot(weights_hidden_output.T)
    hidden_delta = hidden_error * sigmoid_derivative(hidden_layer_output)
    return output_delta, hidden_delta

def update_weights(X, hidden_layer_output, output_delta, weights_input_hidden, weights_hidden_output, learning_rate):
    weights_hidden_output += hidden_layer_output.T.dot(output_delta) * learning_rate
    weights_input_hidden += X.T.dot(hidden_delta) * learning_rate
    return weights_input_hidden, weights_hidden_output

# Define the task (e.g., XOR)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Define the neural network architecture
input_size = 2
hidden_size = 4
output_size = 1

# Initialize weights
weights_input_hidden, weights_hidden_output = initialize_weights(input_size, hidden_size, output_size)

# Training parameters
learning_rate = 0.1
epochs = 10000

# Training loop
for epoch in range(epochs):
    # Forward propagation
    hidden_layer_output, output_layer_output = forward_propagation(X, weights_input_hidden, weights_hidden_output)

    # Backpropagation
    output_delta, hidden_delta = backpropagation(X, y, hidden_layer_output, output_layer_output, weights_hidden_output)

    # Update weights
    weights_input_hidden, weights_hidden_output = update_weights(X, hidden_layer_output, output_delta, weights_input_hidden, weights_hidden_output, learning_rate)

    # Print the loss every 1000 epochs
    if epoch % 1000 == 0:
        loss = np.mean(np.square(output_delta))
        print(f"Epoch {epoch}, Loss: {loss}")

# Test the trained network
_, final_output = forward_propagation(X, weights_input_hidden, weights_hidden_output)
print("\nFinal Output:")
print(final_output)


Epoch 0, Loss: 0.014289272308712329
Epoch 1000, Loss: 0.011226292092449113
Epoch 2000, Loss: 0.009218060275883028
Epoch 3000, Loss: 0.007016370857863089
Epoch 4000, Loss: 0.0020108103191735756
Epoch 5000, Loss: 0.0003612079458874026
Epoch 6000, Loss: 0.0001293679082017331
Epoch 7000, Loss: 6.459424445205113e-05
Epoch 8000, Loss: 3.825477867909053e-05
Epoch 9000, Loss: 2.5125083433008495e-05

Final Output:
[[0.0741223 ]
 [0.94842511]
 [0.92885169]
 [0.06584961]]
